[package]
name = "ln-lib"
description = "A little lib to scrape lightnovels"
version = "1.1.0"
repository = "https://github.com/HaxSam/ln-scraper"
license = "MIT"
edition = "2021"

[dependencies]
surf = "2.3.2"
serde = "1.0.89"
scraper = "0.12.0"
tokio = { version = "1.17.0", features = ["full"] }
